import { PermissionsBitField } from "discord.js";

export const RawPermissions = {
    "CREATE_INSTANT_INVITE": 1 << 0,
    "KICK_MEMBERS": 1 << 1,
    "BAN_MEMBERS": 1 << 2,
    "ADMINISTRATOR": 1 << 3,
    "MANAGE_CHANNELS": 1 << 4,
    "MANAGE_GUILD": 1 << 5,
    "ADD_REACTIONS": 1 << 6,
    "VIEW_AUDIT_LOG": 1 << 7,
    "PRIORITY_SPEAKER": 1 << 8,
    "STREAM": 1 << 9,
    "VIEW_CHANNEL": 1 << 10,
    "SEND_MESSAGES": 1 << 11,
    "SEND_TTS_MESSAGES": 1 << 12,
    "MANAGE_MESSAGES": 1 << 13,
    "EMBED_LINKS": 1 << 14,
    "ATTACH_FILES": 1 << 15,
    "READ_MESSAGE_HISTORY": 1 << 16,
    "MENTION_EVERYONE": 1 << 17,
    "USE_EXTERNAL_EMOJIS": 1 << 18,
    "VIEW_GUILD_INSIGHTS": 1 << 19,
    "CONNECT": 1 << 20,
    "SPEAK": 1 << 21,
    "MUTE_MEMBERS": 1 << 22,
    "DEAFEN_MEMBERS": 1 << 23,
    "MOVE_MEMBERS": 1 << 24,
    "USE_VAD": 1 << 25,
    "CHANGE_NICKNAME": 1 << 26,
    "MANAGE_NICKNAMES": 1 << 27,
    "MANAGE_ROLES": 1 << 28,
    "MANAGE_WEBHOOKS": 1 << 29,
    "MANAGE_EMOJIS_AND_STICKERS": 1 << 30,
    "USE_APPLICATION_COMMANDS": 1 << 31,
    "REQUEST_TO_SPEAK": 1 << 32,
    "MANAGE_EVENTS": 1 << 33,
    "MANAGE_THREADS": 1 << 34,
    "CREATE_PUBLIC_THREADS": 1 << 35,
    "CREATE_PRIVATE_THREADS": 1 << 36,
    "USE_EXTERNAL_STICKERS": 1 << 37,
    "SEND_MESSAGES_IN_THREADS": 1 << 38,
    "USE_EMBEDDED_ACTIVITIES": 1 << 39,
    "MODERATE_MEMBERS": 1 << 40
};

export const permissions = {
    "CREATE_INSTANT_INVITE": PermissionsBitField.resolve('CreateInstantInvite'),
    "KICK_MEMBERS": PermissionsBitField.resolve('KickMembers'),
    "BAN_MEMBERS": PermissionsBitField.resolve('BanMembers'),
    "ADMINISTRATOR": PermissionsBitField.resolve('Administrator'),
    "MANAGE_CHANNELS": PermissionsBitField.resolve('ManageChannels'),
    "MANAGE_GUILD": PermissionsBitField.resolve('ManageGuild'),
    "ADD_REACTIONS": PermissionsBitField.resolve('AddReactions'),
    "VIEW_AUDIT_LOG": PermissionsBitField.resolve('ViewAuditLog'),
    "PRIORITY_SPEAKER": PermissionsBitField.resolve('PrioritySpeaker'),
    "STREAM": PermissionsBitField.resolve('Stream'),
    "VIEW_CHANNEL": PermissionsBitField.resolve('ViewChannel'),
    "SEND_MESSAGES": PermissionsBitField.resolve('SendMessages'),
    "SEND_TTS_MESSAGES": PermissionsBitField.resolve('SendTTSMessages'),
    "MANAGE_MESSAGES": PermissionsBitField.resolve('ManageMessages'),
    "EMBED_LINKS": PermissionsBitField.resolve('EmbedLinks'),
    "ATTACH_FILES": PermissionsBitField.resolve('AttachFiles'),
    "READ_MESSAGE_HISTORY": PermissionsBitField.resolve('ReadMessageHistory'),
    "MENTION_EVERYONE": PermissionsBitField.resolve('MentionEveryone'),
    "USE_EXTERNAL_EMOJIS": PermissionsBitField.resolve('UseExternalEmojis'),
    "VIEW_GUILD_INSIGHTS": PermissionsBitField.resolve('ViewGuildInsights'),
    "CONNECT": PermissionsBitField.resolve('Connect'),
    "SPEAK": PermissionsBitField.resolve('Speak'),
    "MUTE_MEMBERS": PermissionsBitField.resolve('MuteMembers'),
    "DEAFEN_MEMBERS": PermissionsBitField.resolve('DeafenMembers'),
    "MOVE_MEMBERS": PermissionsBitField.resolve('MoveMembers'),
    "USE_VAD": PermissionsBitField.resolve('UseVAD'),
    "CHANGE_NICKNAME": PermissionsBitField.resolve('ChangeNickname'),
    "MANAGE_NICKNAMES": PermissionsBitField.resolve('ManageNicknames'),
    "MANAGE_ROLES": PermissionsBitField.resolve('ManageRoles'),
    "MANAGE_WEBHOOKS": PermissionsBitField.resolve('ManageWebhooks'),
    "MANAGE_EMOJIS_AND_STICKERS": PermissionsBitField.resolve('ManageEmojisAndStickers'),
    "USE_APPLICATION_COMMANDS": PermissionsBitField.resolve('UseApplicationCommands'),
    "REQUEST_TO_SPEAK": PermissionsBitField.resolve('RequestToSpeak'),
    "MANAGE_EVENTS": PermissionsBitField.resolve('ManageEvents'),
    "MANAGE_THREADS": PermissionsBitField.resolve('ManageThreads'),
    "CREATE_PUBLIC_THREADS": PermissionsBitField.resolve('CreatePublicThreads'),
    "CREATE_PRIVATE_THREADS": PermissionsBitField.resolve('CreatePrivateThreads'),
    "USE_EXTERNAL_STICKERS": PermissionsBitField.resolve('UseExternalStickers'),
    "SEND_MESSAGES_IN_THREADS": PermissionsBitField.resolve('SendMessagesInThreads'),
    "USE_EMBEDDED_ACTIVITIES": PermissionsBitField.resolve('UseEmbeddedActivities'),
    "MODERATE_MEMBERS": PermissionsBitField.resolve('ModerateMembers')
};